// Premium Luxury Fashion Ecommerce Mock Data

export const categories = [
  { id: 'cat-1', name: 'Essentials', slug: 'essentials', count: 18, image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800' },
  { id: 'cat-2', name: 'Outerwear', slug: 'outerwear', count: 12, image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=800' },
  { id: 'cat-3', name: 'Tailoring', slug: 'tailoring', count: 8, image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800' },
  { id: 'cat-4', name: 'Footwear', slug: 'footwear', count: 10, image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800' },
  { id: 'cat-5', name: 'Accessories', slug: 'accessories', count: 15, image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800' },
];

export const products = [
  {
    id: 'prod-1',
    name: 'Atelier Heavyweight Oversized Tee',
    slug: 'atelier-heavyweight-oversized-tee',
    category: 'essentials',
    description: 'Cut from substantial 300gsm dry-cotton jersey. Features a boxy silhouette, dropped shoulders, and a thick ribbed collar that holds its shape. A cornerstone of the minimalist daily uniform.',
    price: 95,
    discountPrice: 80,
    stock: 24,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Off-White', 'Black', 'Charcoal'],
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=1000',
    ],
    rating: 4.8,
    reviewsCount: 42,
    featured: true,
  },
  {
    id: 'prod-2',
    name: 'Monomatic Brushed Calf Leather Jacket',
    slug: 'monomatic-brushed-calf-leather-jacket',
    category: 'outerwear',
    description: 'Expertly tailored from full-grain vegetable-tanned calf leather. Features customized matte black hardware, double-stitched paneling, and a Japanese cupro lining for an extremely smooth, premium feel.',
    price: 890,
    discountPrice: null,
    stock: 7,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Charcoal'],
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&q=80&w=1000',
    ],
    rating: 4.9,
    reviewsCount: 18,
    featured: true,
  },
  {
    id: 'prod-3',
    name: 'Sculpted Silhouette Wool Blazer',
    slug: 'sculpted-silhouette-wool-blazer',
    category: 'tailoring',
    description: 'A sharp, double-breasted blazer constructed from premium Italian virgin wool. Features clean structured shoulders, notched lapels, and subtle welt pockets. Tailored to perfection for a timeless shape.',
    price: 480,
    discountPrice: 420,
    stock: 12,
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Charcoal', 'Cream'],
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=1000',
    ],
    rating: 4.7,
    reviewsCount: 29,
    featured: true,
  },
  {
    id: 'prod-4',
    name: 'Minimalist Technical Cargo Pant',
    slug: 'minimalist-technical-cargo-pant',
    category: 'essentials',
    description: 'Constructed from lightweight, water-resistant Japanese nylon ripstop. Features articulated knees for maximum mobility, invisible zippered side utility pockets, and adjustable toggle hems.',
    price: 180,
    discountPrice: null,
    stock: 15,
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Charcoal', 'Black'],
    images: [
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=1000',
    ],
    rating: 4.6,
    reviewsCount: 33,
    featured: false,
  },
  {
    id: 'prod-5',
    name: 'Atelier Brushed Suede Sneaker',
    slug: 'atelier-brushed-suede-sneaker',
    category: 'footwear',
    description: 'Handcrafted in Italy using exceptionally soft premium calf suede. Features a stitched margom rubber cupsole, minimalist blind eyelets, and natural calfskin lining for ultimate comfort and durability.',
    price: 290,
    discountPrice: 240,
    stock: 9,
    sizes: ['40', '41', '42', '43', '44', '45'],
    colors: ['Cream', 'Charcoal', 'Black'],
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=1000',
    ],
    rating: 4.9,
    reviewsCount: 51,
    featured: true,
  },
  {
    id: 'prod-6',
    name: 'Matte Brushed Titanium Chronograph',
    slug: 'matte-brushed-titanium-chronograph',
    category: 'accessories',
    description: 'An elegant utility accessory featuring a sandblasted titanium casing, a premium scratch-resistant sapphire crystal lens, and a high-accuracy Swiss quartz movement. Waterproof up to 50 meters.',
    price: 520,
    discountPrice: null,
    stock: 5,
    sizes: ['One Size'],
    colors: ['Black', 'Charcoal'],
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=1000',
    ],
    rating: 4.8,
    reviewsCount: 14,
    featured: true,
  },
  {
    id: 'prod-7',
    name: 'Atelier Cashmere Oversized Hoodie',
    slug: 'atelier-cashmere-oversized-hoodie',
    category: 'essentials',
    description: 'Knit from pure, ethically sourced Mongolian cashmere. Incredibly lightweight yet provides exceptional warmth. Features double-faced hood construction, ribbed cuffs, and clean minimal side slit pockets.',
    price: 320,
    discountPrice: 280,
    stock: 16,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Charcoal', 'Cream', 'Black'],
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1517242046021-82ee12d03b14?auto=format&fit=crop&q=80&w=1000',
    ],
    rating: 4.9,
    reviewsCount: 22,
    featured: false,
  },
  {
    id: 'prod-8',
    name: 'Atelier Leather Duffle Bag',
    slug: 'atelier-leather-duffle-bag',
    category: 'accessories',
    description: 'A spacious travel bag built from pebbled French calfskin leather. Designed with a structured baseline, heavy-duty gunmetal zipper, detatchable padded shoulder strap, and dedicated internal laptop sleeve.',
    price: 450,
    discountPrice: null,
    stock: 8,
    sizes: ['One Size'],
    colors: ['Black'],
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1547949003-9792a18a2601?auto=format&fit=crop&q=80&w=1000',
    ],
    rating: 4.7,
    reviewsCount: 19,
    featured: false,
  },
];

export const reviews = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    userName: 'Alexander V.',
    rating: 5,
    comment: 'The weight of the cotton is absolute perfection. Standard high-end shirts usually feel too thin, but this holds structure marvelously.',
    date: '2026-04-12',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    userName: 'Elena R.',
    rating: 4,
    comment: 'Beautiful fit and drape. Dropped shoulder is cut perfectly. I highly recommend sizing down if you prefer a less dramatic boxy outline.',
    date: '2026-05-01',
  },
  {
    id: 'rev-3',
    productId: 'prod-2',
    userName: 'Marcus K.',
    rating: 5,
    comment: 'Absolute masterclass in leather tailoring. The cupro lining is silky smooth and matte black zippers feel incredibly solid.',
    date: '2026-04-29',
  },
];

export const testimonials = [
  {
    id: 't-1',
    name: 'Hélène Dubois',
    role: 'Creative Director',
    quote: 'Finding garments that embody true minimalist restraint without compromising textile weight or stitching quality has always been a challenge. Their pieces are structural works of art.',
    avatar: 'HD',
  },
  {
    id: 't-2',
    name: 'Soren Nielsen',
    role: 'Architectural Designer',
    quote: 'The architectural structure of the heavy tees and tailoring blazer is flawless. They sit cleanly, maintain crisp lines, and wear beautifully across seasons.',
    avatar: 'SN',
  },
  {
    id: 't-3',
    name: 'Kai Tanaka',
    role: 'Visual Artist',
    quote: 'The monochrome palette is deep and sophisticated. There are no distracting details—just rich cashmere, premium leather, and impeccable form.',
    avatar: 'KT',
  },
];

export const users = [
  {
    id: 'usr-101',
    name: 'Julian Sterling',
    email: 'sterling@atelier.com',
    role: 'Member',
    avatar: 'JS',
    addresses: [
      {
        id: 'addr-1',
        label: 'Primary Atelier Residence',
        street: '144 Crosby Street, Suite 4B',
        city: 'New York',
        state: 'NY',
        zip: '10012',
        country: 'United States',
        default: true,
      },
      {
        id: 'addr-2',
        label: 'Paris Pied-à-Terre',
        street: '18 Rue du Faubourg Saint-Honoré',
        city: 'Paris',
        state: 'IDF',
        zip: '75008',
        country: 'France',
        default: false,
      },
    ],
  },
];

export const orders = [
  {
    id: 'ORD-9883',
    date: '2026-05-10',
    status: 'Delivered',
    total: 975,
    paymentMethod: 'Apple Pay',
    items: [
      {
        id: 'item-1',
        productId: 'prod-2',
        name: 'Monomatic Brushed Calf Leather Jacket',
        size: 'L',
        color: 'Black',
        price: 890,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=300',
      },
      {
        id: 'item-2',
        productId: 'prod-1',
        name: 'Atelier Heavyweight Oversized Tee',
        size: 'L',
        color: 'Off-White',
        price: 85,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=300',
      },
    ],
    shippingAddress: {
      street: '144 Crosby Street, Suite 4B',
      city: 'New York',
      state: 'NY',
      zip: '10012',
      country: 'United States',
    },
  },
  {
    id: 'ORD-9114',
    date: '2026-04-18',
    status: 'Delivered',
    total: 240,
    paymentMethod: 'Visa Ending in 4088',
    items: [
      {
        id: 'item-3',
        productId: 'prod-5',
        name: 'Atelier Brushed Suede Sneaker',
        size: '43',
        color: 'Cream',
        price: 240,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=300',
      },
    ],
    shippingAddress: {
      street: '144 Crosby Street, Suite 4B',
      city: 'New York',
      state: 'NY',
      zip: '10012',
      country: 'United States',
    },
  },
];
